version: "3.7"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "password123!"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
        container_name: db1
        hostname: db1
  